name: Test CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Merge main -> develop
        uses: everlytic/branch-merge@1.1.2
        with:
          github_token: ${{ github.token }}
          source_ref: ${{ github.ref }}
          target_branch: 'dev'
          commit_message_template: 'Merge main into {target_branch}'
      - name: Create Pull Request
        if: failure()
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ github.token }}
          branch: main
          branch-suffix: timestamp
          base: dev
          delete-branch: true
          title: 'Merge main -> develop (resolve conflict)'
          body: |
            :crown: *An automated PR*

            Resolve the conflict and then merge
          labels: |
            automated pr
          draft: false