name: Test CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Merge main -> develop
        uses: everlytic/branch-merge@1.1.2
        with:
          github_token: ${{ github.token }}
          source_ref: ${{ github.ref }}
          target_branch: 'dev'
          commit_message_template: 'Merge main into {target_branch}'
      - name: Create branch
        if: failure()
        run: |
          git checkout -b chore/sync-main-to-dev-${{ github.run_id }}-${{ github.run_attempt }}
      - name: Create pull request merge conflict
        if: failure()
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ github.token }}
          title: 'Merge main -> develop (resolve conflict)'
          commit-message: Merge main -> develop (resolve conflict)
          branch: chore/sync-main-to-dev-${{ github.run_id }}-${{ github.run_attempt }}
          base: dev
          delete-branch: true
          labels: |
            automated pr
          draft: false
